# Generated by Django 3.2.4 on 2021-07-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('nombre_repuesto', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('precio_producto', models.IntegerField()),
                ('descripcion_producto', models.TextField()),
            ],
        ),
    ]
